"""pokemove_add

Revision ID: 1c10d28d7c92
Revises: 68411e637b69
Create Date: 2023-10-28 18:30:43.051382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c10d28d7c92'
down_revision: Union[str, None] = '68411e637b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemoves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Pokemon_id', sa.Integer(), nullable=True),
    sa.Column('move_id', sa.Integer(), nullable=True),
    sa.Column('learn_probability', sa.Float(), nullable=True),
    sa.Column('can_learn', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['Pokemon_id'], ['pokemons.id'], ),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemoves_id'), 'pokemoves', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemoves_id'), table_name='pokemoves')
    op.drop_table('pokemoves')
    # ### end Alembic commands ###
