"""fix typo

Revision ID: 7ba4ecd6642d
Revises: 03884b6f06b2
Create Date: 2023-10-31 14:45:12.088908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba4ecd6642d'
down_revision: Union[str, None] = '03884b6f06b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemoves', sa.Column('pokemon_id', sa.Integer(), nullable=True))
    op.drop_constraint('pokemoves_Pokemon_id_fkey', 'pokemoves', type_='foreignkey')
    op.create_foreign_key(None, 'pokemoves', 'pokemons', ['pokemon_id'], ['id'])
    op.drop_column('pokemoves', 'Pokemon_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemoves', sa.Column('Pokemon_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pokemoves', type_='foreignkey')
    op.create_foreign_key('pokemoves_Pokemon_id_fkey', 'pokemoves', 'pokemons', ['Pokemon_id'], ['id'])
    op.drop_column('pokemoves', 'pokemon_id')
    # ### end Alembic commands ###
